# -*- coding: utf-8 -*-
"""08_yolov8m_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFI7hrSRLM-PzJhtcm6R3EExrdsf-dNX

# YOLOv8m Training & Evaluation Notebook

This notebook trains YOLOv8m with GPU verification and recall optimization.

## Objectives:
- GPU verification (CUDA, PyTorch)
- Train YOLOv8m with class-weighted loss
- Transfer learning from yolov8m.pt
- Maximize recall for Theft class
- Early stopping and patience tuning
- Confidence threshold optimization
"""

# تثبيت gdown
!pip install -q gdown

import gdown

# ملف dataset من Google Drive
url = "https://drive.google.com/uc?id=1SNRpe37B8SZ7yHbqjIASdZ45_5IOSuj8"

# تحميل zip
gdown.download(url, "dataset.zip", quiet=False)

# فك الضغط
!unzip -o dataset.zip -d /content/dataset

# عرض المحتوى
!ls -la /content/dataset

# ==================== COLAB SETUP ====================
print("🚀 Setting up Google Colab environment (NO DRIVE)...")

# Install Ultralytics + gdown
print("\n📦 Installing Ultralytics & gdown...")
!pip install -q ultralytics gdown

# Download & extract dataset
import gdown
import zipfile
from pathlib import Path

# Google Drive FILE ID (dataset.zip)
FILE_ID = "1SNRpe37B8SZ7yHbqjIASdZ45_5IOSuj8"

DATASET_ZIP = "/content/dataset.zip"
EXTRACT_TO = "/content/dataset"

print("\n⬇️ Downloading dataset from Google Drive...")
url = f"https://drive.google.com/uc?id={FILE_ID}"
gdown.download(url, DATASET_ZIP, quiet=False)

print("\n📂 Extracting dataset...")
Path(EXTRACT_TO).mkdir(exist_ok=True)

with zipfile.ZipFile(DATASET_ZIP, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_TO)

print(f"✅ Dataset extracted to: {EXTRACT_TO}")

# List contents
print("\n📁 Dataset structure:")
!ls -la {EXTRACT_TO}
!ls -la {EXTRACT_TO}/AletrixGrad-dataset/

# Import required libraries
import torch
import torchvision
import yaml
from pathlib import Path
from ultralytics import YOLO
import matplotlib.pyplot as plt
import pandas as pd

# GPU Verification (CRITICAL - CPU training NOT allowed)
print("="*80)
print("GPU VERIFICATION")
print("="*80)

if torch.cuda.is_available():
    print(f"✓ CUDA is available")
    print(f"✓ GPU Device: {torch.cuda.get_device_name(0)}")
    print(f"✓ CUDA Version: {torch.version.cuda}")
    print(f"✓ PyTorch Version: {torch.__version__}")
    print(f"✓ GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")
    print(f"✓ GPU will be used for training")
    DEVICE = 0
else:
    print("✗ ERROR: CUDA is not available!")
    print("✗ CPU training is NOT allowed. Please ensure:")
    print("  1. NVIDIA GPU with CUDA support is installed")
    print("  2. CUDA toolkit is installed")
    print("  3. PyTorch with CUDA support is installed")
    print("\nAborting training...")
    raise RuntimeError("GPU not available - training aborted")

"""## Load Dataset Configuration"""

from pathlib import Path
import yaml

# Possible dataset.yaml locations
candidates = [
    Path("/content/dataset/dataset_processed/data.yaml"),
    Path("/content/dataset/AletrixGrad-dataset/data.yaml"),
]

DATA_YAML = None
for path in candidates:
    if path.exists():
        DATA_YAML = path
        break

if DATA_YAML is None:
    raise FileNotFoundError(
        "❌ data.yaml not found. Checked:\n" +
        "\n".join(str(p) for p in candidates)
    )

with open(DATA_YAML, "r") as f:
    config = yaml.safe_load(f)

print(f"✅ Dataset configuration loaded from: {DATA_YAML}")
print(f"📦 Number of classes: {config['nc']}")
print(f"🏷️ Class names: {config['names']}")

"""## Train YOLOv8m Model"""

# Initialize YOLOv8m model (transfer learning from pre-trained weights)
model = YOLO('yolov8m.pt')  # Load pre-trained YOLOv8m weights

# Training configuration optimized for Theft detection
# Focus on maximizing recall for Theft class (class ID 5)
training_config = {
    'data': str(DATA_YAML.absolute()),
    'epochs': 50,
    'imgsz': 640,
    'batch': 16,  # Adjust based on GPU memory
    'device': DEVICE,
    'workers': 8,
    'cache': True,  # Enable dataset caching for faster training
    'optimizer': 'AdamW',  # AdamW optimizer
    'lr0': 0.001,  # Initial learning rate
    'lrf': 0.01,  # Final learning rate (lr0 * lrf)
    'momentum': 0.937,
    'weight_decay': 0.0005,
    'warmup_epochs': 3.0,
    'warmup_momentum': 0.8,
    'warmup_bias_lr': 0.1,
    'box': 7.5,  # Box loss gain
    'cls': 0.5,  # Class loss gain
    'dfl': 1.5,  # DFL loss gain
    'pose': 12.0,
    'kobj': 1.0,
    'label_smoothing': 0.0,
    'nbs': 64,  # Nominal batch size
    'hsv_h': 0.015,  # HSV-Hue augmentation
    'hsv_s': 0.7,  # HSV-Saturation augmentation
    'hsv_v': 0.4,  # HSV-Value augmentation
    'degrees': 0.0,  # Rotation (+/- deg)
    'translate': 0.1,  # Translation (+/- fraction)
    'scale': 0.5,  # Scale (+/- gain)
    'shear': 0.0,  # Shear (+/- deg)
    'perspective': 0.0,  # Perspective (+/- fraction)
    'flipud': 0.0,  # Flip up-down (probability)
    'fliplr': 0.5,  # Flip left-right (probability)
    'mosaic': 1.0,  # Mosaic augmentation (probability)
    'mixup': 0.0,  # Mixup augmentation (probability)
    'copy_paste': 0.0,  # Copy-paste augmentation (probability)
    'close_mosaic': 10,  # Disable mosaic augmentation for last N epochs
    'patience': 50,  # Early stopping patience
    'save': True,
    'save_period': 10,  # Save checkpoint every N epochs
    'project': 'runs/detect',
    'name': 'yolov8m_theft_detection',
    'exist_ok': True,
    'pretrained': True,
    'verbose': True,
    'seed': 42,
    'deterministic': True,
    'single_cls': False,
    'rect': False,
    'cos_lr': False,
    'resume': False,
    'amp': True,  # Automatic Mixed Precision (AMP) training
    'fraction': 1.0,
    'profile': False,
    'overlap_mask': True,
    'mask_ratio': 4,
    'dropout': 0.0,
}

print("Training Configuration:")
print("="*80)
for key, value in training_config.items():
    print(f"  {key}: {value}")

# Start training
print("\n" + "="*80)
print("Starting YOLOv8m Training...")
print("="*80)

results = model.train(**training_config)

"""## Evaluation & Metrics"""

# البحث عن index كلمة theft (تأكد أن الكلمة مكتوبة بنفس الطريقة في data.yaml)
try:
    theft_class_id = config['names'].index('theft')

    print(f"\nTheft Class Metrics:")
    # استخدمنا .p و .r و .maps للوصول للقيم الخاصة بكل كلاس
    print(f"  Precision: {metrics.box.p[theft_class_id]:.4f}")
    print(f"  Recall: {metrics.box.r[theft_class_id]:.4f}")
    print(f"  mAP50: {metrics.box.maps[theft_class_id]:.4f}")
except ValueError:
    print("❌ Class 'theft' not found in dataset names.")
except IndexError:
    print("❌ Could not access metrics for the specific class. Check if the model evaluated all classes.")

# Install Ultralytics
!pip install -q ultralytics

import pandas as pd
from IPython.display import display
from ultralytics import YOLO
import yaml
from pathlib import Path
import gdown
import zipfile # Still imported for consistency, but not used for unzip

# Google Drive FILE ID (dataset.zip) - ensure this is the correct ID
FILE_ID = "1SNRpe37B8SZ7yHbqjIASdZ45_5IOSuj8"
DATASET_ZIP = "/content/dataset.zip"
EXTRACT_TO = "/content/dataset"

print("\n⬇️ Re-downloading dataset from Google Drive for evaluation...")
url = f"https://drive.google.com/uc?id={FILE_ID}"
gdown.download(url, DATASET_ZIP, quiet=False)

print("\n📂 Re-extracting dataset...")
Path(EXTRACT_TO).mkdir(exist_ok=True)

# Use the unzip shell command for more robust extraction
!unzip -o {DATASET_ZIP} -d {EXTRACT_TO}

print(f"✅ Dataset re-extracted to: {EXTRACT_TO}")

# Re-initialize DATA_YAML and config
candidates = [
    Path("/content/dataset/dataset_processed/data.yaml"),
    Path("/content/dataset/AletrixGrad-dataset/data.yaml"),
]

DATA_YAML = None
for path in candidates:
    if path.exists():
        DATA_YAML = path
        break

if DATA_YAML is None:
    raise FileNotFoundError(
        "❌ data.yaml not found. Checked:\n" +
        "\n".join(str(p) for p in candidates)
    )

with open(DATA_YAML, "r") as f:
    config = yaml.safe_load(f)

# Re-initialize the model
model = YOLO('yolov8m.pt')

# Define PROJECT_DIR and RUN_NAME for saving results
PROJECT_DIR = 'runs/detect'
RUN_NAME = 'yolov8m_theft_detection'

# 1. Run validation to get fresh metrics
print("Evaluating model performance...")
metrics = model.val()

# 2. Extract class names from the model
class_names = list(model.names.values())

# 3. Create a dictionary to store metrics for each class
class_results = []
for i, name in enumerate(class_names):
    # Get metrics for each specific class
    results_dict = {
        "Class": name,
        "Precision": f"{metrics.box.p[i]:.4f}",
        "Recall": f"{metrics.box.r[i]:.4f}",
        "mAP50": f"{metrics.box.maps[i]:.4f}",
        "mAP50-95": f"{metrics.box.map:.4f}" # This is usually the global map
    }
    class_results.append(results_dict)

# 4. Convert to a beautiful Pandas DataFrame
df_results = pd.DataFrame(class_results)

# 5. Display the table
print("\n" + "="*50)
print("📊 FINAL CLASS-WISE ACCURACY METRICS")
print("="*50)
display(df_results)

# 6. Optional: Save these results to a CSV file (useful for your project documentation)
results_csv_path = f"{PROJECT_DIR}/{RUN_NAME}/final_class_metrics.csv"
df_results.to_csv(results_csv_path, index=False)
print(f"\n✅ Metrics saved to: {results_csv_path}")

import os
import shutil
from google.colab import files

# 1. Define the path where weights are saved
# Based on your previous setup: runs/detect/yolov8m_theft_detection/weights
weights_path = f'{PROJECT_DIR}/{RUN_NAME}/weights'

# 2. Check if the directory exists
if os.path.exists(weights_path):
    print(f"📦 Found weights at: {weights_path}")

    # List files to be sure (best.pt, last.pt)
    print("Files to download:", os.listdir(weights_path))

    # 3. Create a zip file of the weights folder
    zip_name = "yolov8m_trained_weights"
    shutil.make_archive(zip_name, 'zip', weights_path)

    print(f"✅ Zipping complete: {zip_name}.zip")

    # 4. Trigger the browser download
    files.download(f"{zip_name}.zip")
    print("🚀 Download started! Check your browser's download folder.")
else:
    print(f"❌ Error: The path {weights_path} was not found. Did the training finish successfully?")